version: '3'

volumes:
  vw-data:
  vw-logs:
  f2b-data:

services:

  vaultwarden:
    image: vaultwarden/server:1.23.0
    restart: always
    expose:
      - 80
    volumes:
      - vw-data:/data
      - vw-logs:/var/log/vw-logs
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_SSL=${SMTP_SSL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

      # - ADMIN_TOKEN=${ADMIN_TOKEN}

      - DOMAIN=${URL_BASE}

      - SIGNUPS_ALLOWED=false
      - SIGNUPS_DOMAINS_WHITELIST=${SIGNUPS_DOMAINS_WHITELIST}
      - SIGNUPS_VERIFY=true
      - INVITATIONS_ALLOWED=true

      # default is to purge the trash every night
      #- TRASH_PURGE_SCHEDULE="0 5 0 * * *"

      - LOG_FILE=/var/log/vw-logs/vaultwarden.log

  fail2ban:
    build:
      context: fail2ban
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    volumes:
      - vw-logs:/var/log/vw-logs:ro
      - f2b-data:/data
    environment:
      # match timezone of vaultwarden container = UTC, do not set TZ
      #- TZ=Europe/Paris

      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=INFO
      - F2B_DB_PURGE_AGE=1d

      - SSMTP_HOST=${SMTP_HOST}
      - SSMTP_PORT=${SMTP_PORT}
      - SSMTP_HOSTNAME=${SSMTP_HOSTNAME}
      - SSMTP_USER=${SMTP_USERNAME}
      - SSMTP_PASSWORD=${SMTP_PASSWORD}
      - SSMTP_TLS=YES

    depends_on:
      - vaultwarden

  proxy:
    image: nginx:1.21.4-alpine
    restart: always
    volumes:
      - ./proxy/templates:/etc/nginx/templates
      - ${PATH_SSL_DIR}:${PATH_SSL_DIR}:ro
    environment:
      - FQDN=${FQDN}
      - PATH_SSL_CERT=${PATH_SSL_CERT}
      - PATH_SSL_KEY=${PATH_SSL_KEY}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - vaultwarden
